Added is_time_fixed definition
Attempt to solve issue on .../qc-env/lib/python3.9/site-packages/isimip_qc/checks/dimensions.py", line 41, in check_time_dimension
    if not file.is_time_fixed and file.dataset.dimensions.get('time') is None:
AttributeError: 'File' object has no attribute 'is_time_fixed'